name: behavior_clone
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.4.13=hecd8cb5_1
  - certifi=2020.12.5=py39hecd8cb5_0
  - freetype=2.10.4=ha233b18_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - jpeg=9b=he5867d9_2
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.3=h23ab428_0
  - mkl=2021.2.0=hecd8cb5_269
  - mkl-service=2.3.0=py39h9ed2024_1
  - mkl_fft=1.3.0=py39h4a7008c_2
  - mkl_random=1.2.1=py39hb2f4e1b_2
  - ncurses=6.2=h0a44026_1
  - numpy=1.20.1=py39hd6e1bb9_0
  - numpy-base=1.20.1=py39h585ceec_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h9ed2024_0
  - pillow=8.2.0=py39h5270095_0
  - pip=21.0.1=py39hecd8cb5_0
  - python=3.9.4=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.15.0=py39hecd8cb5_0
  - sqlite=3.35.4=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
